---
driver:
  name: vagrant
  network:
  - ["private_network", {ip: "192.168.15.21"}]

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.10

suites:
  - name: default
    run_list:
    - hadoop-java8::default
    attributes:
