---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: debian-7.7

suites:
  - name: default
    run_list:
    - hadoop-java8::default
    attributes:
